spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: my-application
      cluster-nodes: localhost:9300
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  messages:
    encoding: UTF-8


server:
  port: 8080
